import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>DEMO: Drift-DAO</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex justify-center justify-items-center h-screen bg-gradient-to-r from-indigo-500 via-purple-700 to-pink-500">
				<video
					className="my-auto"
					autoPlay
					loop
					controls
					style={{ width: '95vw', height: '95vh', backgroundColor: 'black' }}
				>
					<source src="/drift-dao-demo.mkv" />
				</video>
				{/* <video src="/drift-dao-demo.mkv"></video> */}
			</div>
		</>
	);
}
